version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install
      - npm install -g jq  # Use npm to install jq globally (Node.js environment)

  build:
    commands:
      - echo Building the Nuxt.js application...
      - npm run build  # Build the SSR application

  post_build:
    commands:
      - echo Deploying the Nuxt.js app to EC2...
      - echo "Retrieving SSH key from Secrets Manager"
      
      # Retrieve SSH private key from Secrets Manager and store it in a temporary file
      - |
        aws secretsmanager get-secret-value --secret-id ssh_private_key --query SecretString --output text > key.json
        export PRIVATE_KEY=$(jq -r '.private-key' key.json)
        echo "$PRIVATE_KEY" > key
        chmod 600 key

      # SSH into the EC2 instance and deploy
      - |
        ssh -v -o StrictHostKeyChecking=no -i key ubuntu@13.232.44.241 << 'EOF'
          echo "Starting SSH connection..."

          echo "Pulling the latest changes from the repository"
          cd /home/ubuntu/nuxt-app || exit 1
          
          npm install || exit 1
          
          npm run build || exit 1
          
          pm2 start .output/server/index.mjs --interpreter=node --name nuxt-app || exit 1
          pm2 save || exit 1
          
          echo "Deployment completed successfully!"
        EOF

artifacts:
  files:
    - '**/*'
  discard-paths: yes
