version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the Nuxt SSR app...
      - npm run build

  post_build:
    commands:
      - mkdir -p output
      - rsync -av --exclude=output ./ output/

artifacts:
  files:
    - '**/*'
  base-directory: output
