version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "STARTING"

  build:
    commands:
      - echo "Skipping build step (No `npm run build` needed)"
      - mkdir -p output
      - echo "Copying files to output directory..."
      - shopt -s dotglob
      - cp -r ./* output/

artifacts:
  files:
    - '**/*'
  base-directory: output

